# Site settings
title: Project Documentation
email: project@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Official documentation for the Project - an open source tool for developers.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: project
repository: username/project

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - about.markdown
  - docs/getting-started.md
  - docs/api.md
  - docs/examples.md
  - docs/faq.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/